services:
  postgres:
    image: postgres:15-alpine
    container_name: sm-database
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    container_name: sm-backend
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "3001:3001"

  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    container_name: sm-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - .env.local
